# Generated by Django 3.2.4 on 2021-06-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sen_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sen_add', models.TextField()),
                ('sen_ph', models.CharField(blank=True, max_length=100, null=True)),
                ('rec_name', models.CharField(blank=True, max_length=100, null=True)),
                ('rec_add', models.TextField()),
                ('rec_ph', models.CharField(blank=True, max_length=100, null=True)),
                ('t_g', models.CharField(blank=True, max_length=100, null=True)),
                ('orgin', models.CharField(blank=True, max_length=100, null=True)),
                ('dest', models.CharField(blank=True, max_length=100, null=True)),
                ('pri', models.CharField(blank=True, max_length=100, null=True)),
                ('nodays', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('rej', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('shipid', models.IntegerField()),
                ('dd', models.CharField(blank=True, max_length=100, null=True)),
                ('dm', models.CharField(blank=True, max_length=100, null=True)),
                ('dy', models.CharField(blank=True, max_length=100, null=True)),
                ('ddd', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='shipd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipid', models.IntegerField()),
                ('shname', models.CharField(blank=True, max_length=100, null=True)),
                ('shorig', models.CharField(blank=True, max_length=100, null=True)),
                ('shdest', models.CharField(blank=True, max_length=100, null=True)),
                ('shdate', models.DateField()),
                ('con_e', models.IntegerField()),
                ('con_f', models.IntegerField()),
                ('con_s', models.IntegerField()),
            ],
        ),
    ]
