# Generated by Django 3.2.4 on 2021-06-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.IntegerField()),
                ('Odate', models.DateField()),
                ('DayofMonth', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('Quarter', models.IntegerField()),
                ('DayofWeek', models.IntegerField()),
                ('DayofYear', models.IntegerField()),
                ('WeekofYear', models.IntegerField()),
                ('Sender', models.CharField(blank=True, max_length=100, null=True)),
                ('Senderphone', models.CharField(blank=True, max_length=100, null=True)),
                ('Receiver', models.CharField(blank=True, max_length=100, null=True)),
                ('Receiverphone', models.CharField(blank=True, max_length=100, null=True)),
                ('Origin', models.CharField(blank=True, max_length=100, null=True)),
                ('Destination', models.CharField(blank=True, max_length=100, null=True)),
                ('Typeofgoods', models.CharField(blank=True, max_length=100, null=True)),
                ('Weight', models.IntegerField()),
                ('Priority', models.CharField(blank=True, max_length=100, null=True)),
                ('Rej', models.IntegerField()),
                ('NoofShipDays', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('ShipID', models.IntegerField()),
            ],
        ),
    ]
