# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: wtikehgsaawspm
          POSTGRES_PASSWORD: 853d155860e702fdab2725cddd1759b245ed2a0336c0bce80f332a3c25212ee1
          POSTGRES_DB: deo2h6rl5cjn11
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        #options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: psycopg2 prerequisites
      run: sudo apt-get install libpq-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Run tests
      run: python manage.py test --keepdb
